DROP TABLE IF EXISTS Film CASCADE;
DROP TABLE IF EXISTS Director CASCADE;
DROP TABLE IF EXISTS Star CASCADE;
DROP TABLE IF EXISTS Writer CASCADE;
DROP TABLE IF EXISTS Person CASCADE;

DROP TABLE IF EXISTS FilmDirector CASCADE;
DROP TABLE IF EXISTS FilmStar CASCADE;
DROP TABLE IF EXISTS FilmWriter CASCADE;

CREATE TABLE IF NOT EXISTS Film(
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    title VARCHAR(255) NOT NULL,
    genre VARCHAR(255) NOT NULL,
    releaseYear INTEGER NOT NULL,
    score INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Person(
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Director(
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    directorCountry VARCHAR(255) NOT NULL,
    personFk INTEGER NOT NULL,
    FOREIGN KEY (personFk) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Star(
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    dob VARCHAR(255) NOT NULL,
    personFk INTEGER NOT NULL,
    FOREIGN KEY (personFk) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Writer(
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    email VARCHAR(255) NOT NULL,
    personFk INTEGER NOT NULL,
    FOREIGN KEY (personFk) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS FilmDirector (
    directorFk INTEGER NOT NULL,
    filmFk INTEGER NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    FOREIGN KEY (directorFk) REFERENCES Director(id),
    FOREIGN KEY (filmFk) REFERENCES Film(id),
    PRIMARY KEY(filmFk, directorFk)
);

CREATE TABLE IF NOT EXISTS FilmStar (
    starFk INTEGER NOT NULL,
    filmFk INTEGER NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    FOREIGN KEY (starFk) REFERENCES Star(id),
    FOREIGN KEY (filmFk) REFERENCES Film(id),
    PRIMARY KEY(filmFk, starFk)
);

CREATE TABLE IF NOT EXISTS FilmWriter (
    writerFk INTEGER NOT NULL,
    filmFk INTEGER NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    FOREIGN KEY (writerFk) REFERENCES Writer(id),
    FOREIGN KEY (filmFk) REFERENCES Film(id),
    PRIMARY KEY(filmFk, writerFk)
);